(cl:in-package dji_osdk_ros-msg)
(cl:export '(EVENT-VAL
          EVENT
          FCTIMESTAMP-VAL
          FCTIMESTAMP
          INTERRUPTREASON-VAL
          INTERRUPTREASON
          RECOVERPROCESS-VAL
          RECOVERPROCESS
          FINISHREASON-VAL
          FINISHREASON
          WAYPOINTINDEX-VAL
          WAYPOINTINDEX
          CURRENTMISSIONEXECNUM-VAL
          CURRENTMISSIONEXECNUM
          FINISHEDALLEXECNUM-VAL
          FINISHEDALLEXECNUM
))