(cl:in-package dji_osdk_ros-msg)
(cl:export '(CELLBREAK-VAL
          CELLBREAK
          SELFCHECKERROR-VAL
          SELFCHECKERROR
          BATTERYCLOSEDREASON-VAL
          BATTERYCLOSEDREASON
          BATSOHSTATE-VAL
          BATSOHSTATE
          MAXCYCLELIMIT-VAL
          MAXCYCLELIMIT
          BATTERYCOMMUNICATIONABNORMAL-VAL
          BATTERYCOMMUNICATIONABNORMAL
          HASCELLBREAK-VAL
          HASCELLBREAK
          HEATSTATE-VAL
          HEATSTATE
))