(cl:in-package dji_osdk_ros-msg)
(cl:export '(ACTIONID-VAL
          ACTIONID
          WAYPOINTV2ACTIONTRIGGERTYPE-VAL
          WAYPOINTV2ACTIONTRIGGERTYPE
          WAYPOINTV2ACTIONACTUATORTYPE-VAL
          WAYPOINTV2ACTIONACTUATORTYPE
          WAYPOINTV2ASSOCIATETRIGGER-VAL
          WAYPOINTV2ASSOCIATETRIGGER
          WAYPOINTV2INTERVALTRIGGER-VAL
          WAYPOINTV2INTERVALTRIGGER
          WAYPOINTV2TRAJECTORYTRIGGER-VAL
          WAYPOINTV2TRAJECTORYTRIGGER
          WAYPOINTV2SAMPLEREACHPOINTTRIGGER-VAL
          WAYPOINTV2SAMPLEREACHPOINTTRIGGER
          WAYPOINTV2CAMERAACTUATOR-VAL
          WAYPOINTV2CAMERAACTUATOR
          WAYPOINTV2GIMBALACTUATOR-VAL
          WAYPOINTV2GIMBALACTUATOR
          WAYPOINTV2AIRCRAFTCONTROLACTUATOR-VAL
          WAYPOINTV2AIRCRAFTCONTROLACTUATOR
))