(cl:in-package dji_osdk_ros-msg)
(cl:export '(ACTUATORINDEX-VAL
          ACTUATORINDEX
          DJIWAYPOINTV2ACTIONACTUATORAIRCRAFTCONTROLOPERATIONTYPE-VAL
          DJIWAYPOINTV2ACTIONACTUATORAIRCRAFTCONTROLOPERATIONTYPE
          WAYPOINTV2AIRCRAFTCONTROLACTUATORFLYING-VAL
          WAYPOINTV2AIRCRAFTCONTROLACTUATORFLYING
          WAYPOINTV2AIRCRAFTCONTROLACTUATORROTATEHEADING-VAL
          WAYPOINTV2AIRCRAFTCONTROLACTUATORROTATEHEADING
))