(cl:in-package dji_osdk_ros-msg)
(cl:export '(VOLTAGENOTSAFETY-VAL
          VOLTAGENOTSAFETY
          VERYLOWVOLTAGEALARM-VAL
          VERYLOWVOLTAGEALARM
          LOWVOLTAGEALARM-VAL
          LOWVOLTAGEALARM
          SERIOUSLOWCAPACITYALARM-VAL
          SERIOUSLOWCAPACITYALARM
          LOWCAPACITYALARM-VAL
          LOWCAPACITYALARM
))