(cl:in-package dji_osdk_ros-msg)
(cl:export '(MISSIONID-VAL
          MISSIONID
          MISSTOTALLEN-VAL
          MISSTOTALLEN
          REPEATTIMES-VAL
          REPEATTIMES
          FINISHEDACTION-VAL
          FINISHEDACTION
          MAXFLIGHTSPEED-VAL
          MAXFLIGHTSPEED
          AUTOFLIGHTSPEED-VAL
          AUTOFLIGHTSPEED
          EXITMISSIONONRCSIGNALLOST-VAL
          EXITMISSIONONRCSIGNALLOST
          GOTOFIRSTWAYPOINTMODE-VAL
          GOTOFIRSTWAYPOINTMODE
          MISSION-VAL
          MISSION
))