(cl:in-package dji_osdk_ros-msg)
(cl:export '(LONGITUDE-VAL
          LONGITUDE
          LATITUDE-VAL
          LATITUDE
          RELATIVEHEIGHT-VAL
          RELATIVEHEIGHT
          WAYPOINTTYPE-VAL
          WAYPOINTTYPE
          HEADINGMODE-VAL
          HEADINGMODE
          CONFIG-VAL
          CONFIG
          DAMPINGDISTANCE-VAL
          DAMPINGDISTANCE
          HEADING-VAL
          HEADING
          TURNMODE-VAL
          TURNMODE
          POSITIONX-VAL
          POSITIONX
          POSITIONY-VAL
          POSITIONY
          POSITIONZ-VAL
          POSITIONZ
          MAXFLIGHTSPEED-VAL
          MAXFLIGHTSPEED
          AUTOFLIGHTSPEED-VAL
          AUTOFLIGHTSPEED
))