(cl:in-package dji_osdk_ros-msg)
(cl:export '(DJIWAYPOINTV2ACTIONACTUATORGIMBALOPERATIONTYPE-VAL
          DJIWAYPOINTV2ACTIONACTUATORGIMBALOPERATIONTYPE
          ACTUATORINDEX-VAL
          ACTUATORINDEX
          WAYPOINTV2GIMBALACTUATORROTATIONPARAM-VAL
          WAYPOINTV2GIMBALACTUATORROTATIONPARAM
))