(cl:in-package dji_osdk_ros-msg)
(cl:export '(ACTUATORINDEX-VAL
          ACTUATORINDEX
          DJIWAYPOINTV2ACTIONACTUATORCAMERAOPERATIONTYPE-VAL
          DJIWAYPOINTV2ACTIONACTUATORCAMERAOPERATIONTYPE
          FOCUSPARAM-VAL
          FOCUSPARAM
          ZOOMPARAM-VAL
          ZOOMPARAM
))