// Generated by gencpp from file dji_osdk_ros/CameraTapZoomPoint.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_CAMERATAPZOOMPOINT_H
#define DJI_OSDK_ROS_MESSAGE_CAMERATAPZOOMPOINT_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/CameraTapZoomPointRequest.h>
#include <dji_osdk_ros/CameraTapZoomPointResponse.h>


namespace dji_osdk_ros
{

struct CameraTapZoomPoint
{

typedef CameraTapZoomPointRequest Request;
typedef CameraTapZoomPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraTapZoomPoint
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::CameraTapZoomPoint > {
  static const char* value()
  {
    return "33200383ac53d55f08577c7641a6b09c";
  }

  static const char* value(const ::dji_osdk_ros::CameraTapZoomPoint&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::CameraTapZoomPoint > {
  static const char* value()
  {
    return "dji_osdk_ros/CameraTapZoomPoint";
  }

  static const char* value(const ::dji_osdk_ros::CameraTapZoomPoint&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::CameraTapZoomPointRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraTapZoomPoint >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraTapZoomPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraTapZoomPoint >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraTapZoomPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraTapZoomPointRequest> should match
// service_traits::DataType< ::dji_osdk_ros::CameraTapZoomPoint >
template<>
struct DataType< ::dji_osdk_ros::CameraTapZoomPointRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraTapZoomPoint >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraTapZoomPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::CameraTapZoomPointResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraTapZoomPoint >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraTapZoomPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraTapZoomPoint >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraTapZoomPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraTapZoomPointResponse> should match
// service_traits::DataType< ::dji_osdk_ros::CameraTapZoomPoint >
template<>
struct DataType< ::dji_osdk_ros::CameraTapZoomPointResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraTapZoomPoint >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraTapZoomPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_CAMERATAPZOOMPOINT_H
