// Generated by gencpp from file dji_osdk_ros/CameraStartShootBurstPhoto.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTBURSTPHOTO_H
#define DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTBURSTPHOTO_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/CameraStartShootBurstPhotoRequest.h>
#include <dji_osdk_ros/CameraStartShootBurstPhotoResponse.h>


namespace dji_osdk_ros
{

struct CameraStartShootBurstPhoto
{

typedef CameraStartShootBurstPhotoRequest Request;
typedef CameraStartShootBurstPhotoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraStartShootBurstPhoto
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhoto > {
  static const char* value()
  {
    return "f01c5147bd72cb4f71d9ae46f34d348e";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhoto&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::CameraStartShootBurstPhoto > {
  static const char* value()
  {
    return "dji_osdk_ros/CameraStartShootBurstPhoto";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhoto&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhotoRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhoto >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhotoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhotoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraStartShootBurstPhotoRequest> should match
// service_traits::DataType< ::dji_osdk_ros::CameraStartShootBurstPhoto >
template<>
struct DataType< ::dji_osdk_ros::CameraStartShootBurstPhotoRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraStartShootBurstPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhotoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhotoResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhoto >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhotoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraStartShootBurstPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhotoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraStartShootBurstPhotoResponse> should match
// service_traits::DataType< ::dji_osdk_ros::CameraStartShootBurstPhoto >
template<>
struct DataType< ::dji_osdk_ros::CameraStartShootBurstPhotoResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraStartShootBurstPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootBurstPhotoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTBURSTPHOTO_H
