// Generated by gencpp from file dji_osdk_ros/CameraStartShootIntervalPhotoRequest.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTOREQUEST_H
#define DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct CameraStartShootIntervalPhotoRequest_
{
  typedef CameraStartShootIntervalPhotoRequest_<ContainerAllocator> Type;

  CameraStartShootIntervalPhotoRequest_()
    : payload_index(0)
    , photo_num_conticap(0)
    , time_interval(0)  {
    }
  CameraStartShootIntervalPhotoRequest_(const ContainerAllocator& _alloc)
    : payload_index(0)
    , photo_num_conticap(0)
    , time_interval(0)  {
  (void)_alloc;
    }



   typedef uint8_t _payload_index_type;
  _payload_index_type payload_index;

   typedef uint8_t _photo_num_conticap_type;
  _photo_num_conticap_type photo_num_conticap;

   typedef int16_t _time_interval_type;
  _time_interval_type time_interval;





  typedef boost::shared_ptr< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraStartShootIntervalPhotoRequest_

typedef ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<std::allocator<void> > CameraStartShootIntervalPhotoRequest;

typedef boost::shared_ptr< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest > CameraStartShootIntervalPhotoRequestPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest const> CameraStartShootIntervalPhotoRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator2> & rhs)
{
  return lhs.payload_index == rhs.payload_index &&
    lhs.photo_num_conticap == rhs.photo_num_conticap &&
    lhs.time_interval == rhs.time_interval;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1b60cc04bce35073619b77f1796df3f0";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1b60cc04bce35073ULL;
  static const uint64_t static_value2 = 0x619b77f1796df3f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/CameraStartShootIntervalPhotoRequest";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"uint8 payload_index #see enum class PayloadIndex in common_type.h\n"
"uint8 photo_num_conticap # 0:reserve 1~254:number 255:keep capturing till stop\n"
"int16 time_interval #/ time interval (second)\n"
;
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.payload_index);
      stream.next(m.photo_num_conticap);
      stream.next(m.time_interval);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraStartShootIntervalPhotoRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest_<ContainerAllocator>& v)
  {
    s << indent << "payload_index: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.payload_index);
    s << indent << "photo_num_conticap: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.photo_num_conticap);
    s << indent << "time_interval: ";
    Printer<int16_t>::stream(s, indent + "  ", v.time_interval);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTOREQUEST_H
