// Generated by gencpp from file dji_osdk_ros/CameraStartShootIntervalPhoto.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTO_H
#define DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTO_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/CameraStartShootIntervalPhotoRequest.h>
#include <dji_osdk_ros/CameraStartShootIntervalPhotoResponse.h>


namespace dji_osdk_ros
{

struct CameraStartShootIntervalPhoto
{

typedef CameraStartShootIntervalPhotoRequest Request;
typedef CameraStartShootIntervalPhotoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CameraStartShootIntervalPhoto
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhoto > {
  static const char* value()
  {
    return "bb20f8f95cde73a4d8b41d0f5a0bdcdf";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhoto&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::CameraStartShootIntervalPhoto > {
  static const char* value()
  {
    return "dji_osdk_ros/CameraStartShootIntervalPhoto";
  }

  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhoto&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhoto >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest> should match
// service_traits::DataType< ::dji_osdk_ros::CameraStartShootIntervalPhoto >
template<>
struct DataType< ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraStartShootIntervalPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhoto >
template<>
struct MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::CameraStartShootIntervalPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse> should match
// service_traits::DataType< ::dji_osdk_ros::CameraStartShootIntervalPhoto >
template<>
struct DataType< ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::CameraStartShootIntervalPhoto >::value();
  }
  static const char* value(const ::dji_osdk_ros::CameraStartShootIntervalPhotoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_CAMERASTARTSHOOTINTERVALPHOTO_H
