// Generated by gencpp from file dji_osdk_ros/FlightAnomaly.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_FLIGHTANOMALY_H
#define DJI_OSDK_ROS_MESSAGE_FLIGHTANOMALY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct FlightAnomaly_
{
  typedef FlightAnomaly_<ContainerAllocator> Type;

  FlightAnomaly_()
    : data(0)  {
    }
  FlightAnomaly_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint32_t _data_type;
  _data_type data;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(IMPACT_IN_AIR)
  #undef IMPACT_IN_AIR
#endif
#if defined(_WIN32) && defined(RANDOM_FLY)
  #undef RANDOM_FLY
#endif
#if defined(_WIN32) && defined(VERTICAL_CONTROL_FAIL)
  #undef VERTICAL_CONTROL_FAIL
#endif
#if defined(_WIN32) && defined(HORIZONTAL_CONTROL_FAIL)
  #undef HORIZONTAL_CONTROL_FAIL
#endif
#if defined(_WIN32) && defined(YAW_CONTROL_FAIL)
  #undef YAW_CONTROL_FAIL
#endif
#if defined(_WIN32) && defined(AIRCRAFT_IS_FALLING)
  #undef AIRCRAFT_IS_FALLING
#endif
#if defined(_WIN32) && defined(STRONG_WIND_LEVEL1)
  #undef STRONG_WIND_LEVEL1
#endif
#if defined(_WIN32) && defined(STRONG_WIND_LEVEL2)
  #undef STRONG_WIND_LEVEL2
#endif
#if defined(_WIN32) && defined(COMPASS_INSTALLATION_ERROR)
  #undef COMPASS_INSTALLATION_ERROR
#endif
#if defined(_WIN32) && defined(IMU_INSTALLATION_ERROR)
  #undef IMU_INSTALLATION_ERROR
#endif
#if defined(_WIN32) && defined(ESC_TEMPERATURE_HIGH)
  #undef ESC_TEMPERATURE_HIGH
#endif
#if defined(_WIN32) && defined(ESC_DISCONNECTED)
  #undef ESC_DISCONNECTED
#endif
#if defined(_WIN32) && defined(GPS_YAW_ERROR)
  #undef GPS_YAW_ERROR
#endif

  enum {
    IMPACT_IN_AIR = 1u,
    RANDOM_FLY = 2u,
    VERTICAL_CONTROL_FAIL = 4u,
    HORIZONTAL_CONTROL_FAIL = 8u,
    YAW_CONTROL_FAIL = 16u,
    AIRCRAFT_IS_FALLING = 32u,
    STRONG_WIND_LEVEL1 = 64u,
    STRONG_WIND_LEVEL2 = 128u,
    COMPASS_INSTALLATION_ERROR = 256u,
    IMU_INSTALLATION_ERROR = 512u,
    ESC_TEMPERATURE_HIGH = 1024u,
    ESC_DISCONNECTED = 2048u,
    GPS_YAW_ERROR = 4096u,
  };


  typedef boost::shared_ptr< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> const> ConstPtr;

}; // struct FlightAnomaly_

typedef ::dji_osdk_ros::FlightAnomaly_<std::allocator<void> > FlightAnomaly;

typedef boost::shared_ptr< ::dji_osdk_ros::FlightAnomaly > FlightAnomalyPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::FlightAnomaly const> FlightAnomalyConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "098979ec2b2d91dd43226500118b8680";
  }

  static const char* value(const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x098979ec2b2d91ddULL;
  static const uint64_t static_value2 = 0x43226500118b8680ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/FlightAnomaly";
  }

  static const char* value(const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Here is an example how to use FlightAnomaly msg:\n"
"#\n"
"# void flightAnomalyCallback(const dji_osdk_ros::FlightAnomaly::ConstPtr & msg)\n"
"# {\n"
"#   uint32_t flightAnomalyData = msg->data;\n"
"#   if(flightAnomalyData)\n"
"#   {\n"
"#     ROS_INFO(\"Flight Anomaly Reported by Flight Controller. Here are details:\");\n"
"#     if(flightAnomalyData && dji_osdk_ros::FlightAnomaly::COMPASS_INSTALLATION_ERROR)\n"
"#     {\n"
"#         ROS_INFO(\"COMPASS_INSTALLATION_ERROR\");\n"
"#     }\n"
"#\n"
"#     if(flightAnomalyData && dji_osdk_ros::FlightAnomaly::IMU_INSTALLATION_ERROR)\n"
"#     {\n"
"#         ROS_INFO(\"IMU_INSTALLATION_ERROR\");\n"
"#     }\n"
"#\n"
"#     // etc...\n"
"#   }\n"
"# }\n"
"#\n"
"#\n"
"\n"
"# constants for anomaly details\n"
"uint32 IMPACT_IN_AIR              = 1     #\n"
"uint32 RANDOM_FLY                 = 2     #\n"
"uint32 VERTICAL_CONTROL_FAIL      = 4     #\n"
"uint32 HORIZONTAL_CONTROL_FAIL    = 8     #\n"
"uint32 YAW_CONTROL_FAIL           = 16    #\n"
"uint32 AIRCRAFT_IS_FALLING        = 32    #\n"
"uint32 STRONG_WIND_LEVEL1         = 64    #\n"
"uint32 STRONG_WIND_LEVEL2         = 128   #\n"
"uint32 COMPASS_INSTALLATION_ERROR = 256   #\n"
"uint32 IMU_INSTALLATION_ERROR     = 512   #\n"
"uint32 ESC_TEMPERATURE_HIGH       = 1024  #\n"
"uint32 ESC_DISCONNECTED           = 2048  #\n"
"uint32 GPS_YAW_ERROR              = 4096  #\n"
"\n"
"#\n"
"uint32 data\n"
"\n"
;
  }

  static const char* value(const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlightAnomaly_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::FlightAnomaly_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_FLIGHTANOMALY_H
