// Generated by gencpp from file dji_osdk_ros/GetAvoidEnable.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_GETAVOIDENABLE_H
#define DJI_OSDK_ROS_MESSAGE_GETAVOIDENABLE_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/GetAvoidEnableRequest.h>
#include <dji_osdk_ros/GetAvoidEnableResponse.h>


namespace dji_osdk_ros
{

struct GetAvoidEnable
{

typedef GetAvoidEnableRequest Request;
typedef GetAvoidEnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAvoidEnable
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::GetAvoidEnable > {
  static const char* value()
  {
    return "12c68a1a9e8bfbd739c56cc5d4af2738";
  }

  static const char* value(const ::dji_osdk_ros::GetAvoidEnable&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::GetAvoidEnable > {
  static const char* value()
  {
    return "dji_osdk_ros/GetAvoidEnable";
  }

  static const char* value(const ::dji_osdk_ros::GetAvoidEnable&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::GetAvoidEnableRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::GetAvoidEnable >
template<>
struct MD5Sum< ::dji_osdk_ros::GetAvoidEnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::GetAvoidEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetAvoidEnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::GetAvoidEnableRequest> should match
// service_traits::DataType< ::dji_osdk_ros::GetAvoidEnable >
template<>
struct DataType< ::dji_osdk_ros::GetAvoidEnableRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::GetAvoidEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetAvoidEnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::GetAvoidEnableResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::GetAvoidEnable >
template<>
struct MD5Sum< ::dji_osdk_ros::GetAvoidEnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::GetAvoidEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetAvoidEnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::GetAvoidEnableResponse> should match
// service_traits::DataType< ::dji_osdk_ros::GetAvoidEnable >
template<>
struct DataType< ::dji_osdk_ros::GetAvoidEnableResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::GetAvoidEnable >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetAvoidEnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_GETAVOIDENABLE_H
