// Generated by gencpp from file dji_osdk_ros/GetGoHomeAltitude.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_GETGOHOMEALTITUDE_H
#define DJI_OSDK_ROS_MESSAGE_GETGOHOMEALTITUDE_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/GetGoHomeAltitudeRequest.h>
#include <dji_osdk_ros/GetGoHomeAltitudeResponse.h>


namespace dji_osdk_ros
{

struct GetGoHomeAltitude
{

typedef GetGoHomeAltitudeRequest Request;
typedef GetGoHomeAltitudeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGoHomeAltitude
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::GetGoHomeAltitude > {
  static const char* value()
  {
    return "481d1603c31c25eb38ff6abb0129e8bf";
  }

  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitude&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::GetGoHomeAltitude > {
  static const char* value()
  {
    return "dji_osdk_ros/GetGoHomeAltitude";
  }

  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitude&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::GetGoHomeAltitudeRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::GetGoHomeAltitude >
template<>
struct MD5Sum< ::dji_osdk_ros::GetGoHomeAltitudeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::GetGoHomeAltitude >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitudeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::GetGoHomeAltitudeRequest> should match
// service_traits::DataType< ::dji_osdk_ros::GetGoHomeAltitude >
template<>
struct DataType< ::dji_osdk_ros::GetGoHomeAltitudeRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::GetGoHomeAltitude >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitudeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::GetGoHomeAltitudeResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::GetGoHomeAltitude >
template<>
struct MD5Sum< ::dji_osdk_ros::GetGoHomeAltitudeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::GetGoHomeAltitude >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitudeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::GetGoHomeAltitudeResponse> should match
// service_traits::DataType< ::dji_osdk_ros::GetGoHomeAltitude >
template<>
struct DataType< ::dji_osdk_ros::GetGoHomeAltitudeResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::GetGoHomeAltitude >::value();
  }
  static const char* value(const ::dji_osdk_ros::GetGoHomeAltitudeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_GETGOHOMEALTITUDE_H
