// Generated by gencpp from file dji_osdk_ros/JoystickParams.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_JOYSTICKPARAMS_H
#define DJI_OSDK_ROS_MESSAGE_JOYSTICKPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct JoystickParams_
{
  typedef JoystickParams_<ContainerAllocator> Type;

  JoystickParams_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
    }
  JoystickParams_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> const> ConstPtr;

}; // struct JoystickParams_

typedef ::dji_osdk_ros::JoystickParams_<std::allocator<void> > JoystickParams;

typedef boost::shared_ptr< ::dji_osdk_ros::JoystickParams > JoystickParamsPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::JoystickParams const> JoystickParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::JoystickParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dji_osdk_ros::JoystickParams_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::JoystickParams_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dji_osdk_ros::JoystickParams_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::JoystickParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b81376c2774ff4f956e5110e01c9db26";
  }

  static const char* value(const ::dji_osdk_ros::JoystickParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb81376c2774ff4f9ULL;
  static const uint64_t static_value2 = 0x56e5110e01c9db26ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/JoystickParams";
  }

  static const char* value(const ::dji_osdk_ros::JoystickParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x   # Control with respect to the x axis of the\n"
"            # DJI::OSDK::Control::HorizontalCoordinate.\n"
"float32 y   # Control with respect to the y axis of the\n"
"            # DJI::OSDK::Control::HorizontalCoordinate.\n"
"float32 z   # Control with respect to the z axis, up is positive.\n"
"float32 yaw #Yaw position/velocity control w.r.t. the ground frame.\n"
;
  }

  static const char* value(const ::dji_osdk_ros::JoystickParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoystickParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::JoystickParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::JoystickParams_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_JOYSTICKPARAMS_H
