// Generated by gencpp from file dji_osdk_ros/MFIOConfig.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_MFIOCONFIG_H
#define DJI_OSDK_ROS_MESSAGE_MFIOCONFIG_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/MFIOConfigRequest.h>
#include <dji_osdk_ros/MFIOConfigResponse.h>


namespace dji_osdk_ros
{

struct MFIOConfig
{

typedef MFIOConfigRequest Request;
typedef MFIOConfigResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MFIOConfig
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::MFIOConfig > {
  static const char* value()
  {
    return "ad06bda475c7f13453680ee626114de0";
  }

  static const char* value(const ::dji_osdk_ros::MFIOConfig&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::MFIOConfig > {
  static const char* value()
  {
    return "dji_osdk_ros/MFIOConfig";
  }

  static const char* value(const ::dji_osdk_ros::MFIOConfig&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::MFIOConfigRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MFIOConfig >
template<>
struct MD5Sum< ::dji_osdk_ros::MFIOConfigRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MFIOConfig >::value();
  }
  static const char* value(const ::dji_osdk_ros::MFIOConfigRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MFIOConfigRequest> should match
// service_traits::DataType< ::dji_osdk_ros::MFIOConfig >
template<>
struct DataType< ::dji_osdk_ros::MFIOConfigRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MFIOConfig >::value();
  }
  static const char* value(const ::dji_osdk_ros::MFIOConfigRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::MFIOConfigResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MFIOConfig >
template<>
struct MD5Sum< ::dji_osdk_ros::MFIOConfigResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MFIOConfig >::value();
  }
  static const char* value(const ::dji_osdk_ros::MFIOConfigResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MFIOConfigResponse> should match
// service_traits::DataType< ::dji_osdk_ros::MFIOConfig >
template<>
struct DataType< ::dji_osdk_ros::MFIOConfigResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MFIOConfig >::value();
  }
  static const char* value(const ::dji_osdk_ros::MFIOConfigResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_MFIOCONFIG_H
