// Generated by gencpp from file dji_osdk_ros/MissionHpAction.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_MISSIONHPACTION_H
#define DJI_OSDK_ROS_MESSAGE_MISSIONHPACTION_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/MissionHpActionRequest.h>
#include <dji_osdk_ros/MissionHpActionResponse.h>


namespace dji_osdk_ros
{

struct MissionHpAction
{

typedef MissionHpActionRequest Request;
typedef MissionHpActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionHpAction
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::MissionHpAction > {
  static const char* value()
  {
    return "067ec5f79e77e0b4c0121e09e733b483";
  }

  static const char* value(const ::dji_osdk_ros::MissionHpAction&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::MissionHpAction > {
  static const char* value()
  {
    return "dji_osdk_ros/MissionHpAction";
  }

  static const char* value(const ::dji_osdk_ros::MissionHpAction&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::MissionHpActionRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MissionHpAction >
template<>
struct MD5Sum< ::dji_osdk_ros::MissionHpActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MissionHpAction >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionHpActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MissionHpActionRequest> should match
// service_traits::DataType< ::dji_osdk_ros::MissionHpAction >
template<>
struct DataType< ::dji_osdk_ros::MissionHpActionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MissionHpAction >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionHpActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::MissionHpActionResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MissionHpAction >
template<>
struct MD5Sum< ::dji_osdk_ros::MissionHpActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MissionHpAction >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionHpActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MissionHpActionResponse> should match
// service_traits::DataType< ::dji_osdk_ros::MissionHpAction >
template<>
struct DataType< ::dji_osdk_ros::MissionHpActionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MissionHpAction >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionHpActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_MISSIONHPACTION_H
