// Generated by gencpp from file dji_osdk_ros/MissionWpUpload.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_MISSIONWPUPLOAD_H
#define DJI_OSDK_ROS_MESSAGE_MISSIONWPUPLOAD_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/MissionWpUploadRequest.h>
#include <dji_osdk_ros/MissionWpUploadResponse.h>


namespace dji_osdk_ros
{

struct MissionWpUpload
{

typedef MissionWpUploadRequest Request;
typedef MissionWpUploadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MissionWpUpload
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::MissionWpUpload > {
  static const char* value()
  {
    return "e18bb47c4399b0ec1e363c0b0e75db0f";
  }

  static const char* value(const ::dji_osdk_ros::MissionWpUpload&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::MissionWpUpload > {
  static const char* value()
  {
    return "dji_osdk_ros/MissionWpUpload";
  }

  static const char* value(const ::dji_osdk_ros::MissionWpUpload&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::MissionWpUploadRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MissionWpUpload >
template<>
struct MD5Sum< ::dji_osdk_ros::MissionWpUploadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MissionWpUpload >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionWpUploadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MissionWpUploadRequest> should match
// service_traits::DataType< ::dji_osdk_ros::MissionWpUpload >
template<>
struct DataType< ::dji_osdk_ros::MissionWpUploadRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MissionWpUpload >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionWpUploadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::MissionWpUploadResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::MissionWpUpload >
template<>
struct MD5Sum< ::dji_osdk_ros::MissionWpUploadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::MissionWpUpload >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionWpUploadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::MissionWpUploadResponse> should match
// service_traits::DataType< ::dji_osdk_ros::MissionWpUpload >
template<>
struct DataType< ::dji_osdk_ros::MissionWpUploadResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::MissionWpUpload >::value();
  }
  static const char* value(const ::dji_osdk_ros::MissionWpUploadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_MISSIONWPUPLOAD_H
