// Generated by gencpp from file dji_osdk_ros/ObtainControlAuthorityRequest.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_OBTAINCONTROLAUTHORITYREQUEST_H
#define DJI_OSDK_ROS_MESSAGE_OBTAINCONTROLAUTHORITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct ObtainControlAuthorityRequest_
{
  typedef ObtainControlAuthorityRequest_<ContainerAllocator> Type;

  ObtainControlAuthorityRequest_()
    : enable_obtain(false)  {
    }
  ObtainControlAuthorityRequest_(const ContainerAllocator& _alloc)
    : enable_obtain(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_obtain_type;
  _enable_obtain_type enable_obtain;





  typedef boost::shared_ptr< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ObtainControlAuthorityRequest_

typedef ::dji_osdk_ros::ObtainControlAuthorityRequest_<std::allocator<void> > ObtainControlAuthorityRequest;

typedef boost::shared_ptr< ::dji_osdk_ros::ObtainControlAuthorityRequest > ObtainControlAuthorityRequestPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::ObtainControlAuthorityRequest const> ObtainControlAuthorityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.enable_obtain == rhs.enable_obtain;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8873bb8e9aa86bd4859be5ee2513dd62";
  }

  static const char* value(const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8873bb8e9aa86bd4ULL;
  static const uint64_t static_value2 = 0x859be5ee2513dd62ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/ObtainControlAuthorityRequest";
  }

  static const char* value(const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"bool enable_obtain\n"
;
  }

  static const char* value(const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_obtain);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObtainControlAuthorityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::ObtainControlAuthorityRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable_obtain: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_obtain);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_OBTAINCONTROLAUTHORITYREQUEST_H
