// Generated by gencpp from file dji_osdk_ros/SDKControlAuthority.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_SDKCONTROLAUTHORITY_H
#define DJI_OSDK_ROS_MESSAGE_SDKCONTROLAUTHORITY_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/SDKControlAuthorityRequest.h>
#include <dji_osdk_ros/SDKControlAuthorityResponse.h>


namespace dji_osdk_ros
{

struct SDKControlAuthority
{

typedef SDKControlAuthorityRequest Request;
typedef SDKControlAuthorityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SDKControlAuthority
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::SDKControlAuthority > {
  static const char* value()
  {
    return "ab9a31a36ad499da6a1bb989580360dd";
  }

  static const char* value(const ::dji_osdk_ros::SDKControlAuthority&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::SDKControlAuthority > {
  static const char* value()
  {
    return "dji_osdk_ros/SDKControlAuthority";
  }

  static const char* value(const ::dji_osdk_ros::SDKControlAuthority&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::SDKControlAuthorityRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SDKControlAuthority >
template<>
struct MD5Sum< ::dji_osdk_ros::SDKControlAuthorityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SDKControlAuthority >::value();
  }
  static const char* value(const ::dji_osdk_ros::SDKControlAuthorityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SDKControlAuthorityRequest> should match
// service_traits::DataType< ::dji_osdk_ros::SDKControlAuthority >
template<>
struct DataType< ::dji_osdk_ros::SDKControlAuthorityRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SDKControlAuthority >::value();
  }
  static const char* value(const ::dji_osdk_ros::SDKControlAuthorityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::SDKControlAuthorityResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SDKControlAuthority >
template<>
struct MD5Sum< ::dji_osdk_ros::SDKControlAuthorityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SDKControlAuthority >::value();
  }
  static const char* value(const ::dji_osdk_ros::SDKControlAuthorityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SDKControlAuthorityResponse> should match
// service_traits::DataType< ::dji_osdk_ros::SDKControlAuthority >
template<>
struct DataType< ::dji_osdk_ros::SDKControlAuthorityResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SDKControlAuthority >::value();
  }
  static const char* value(const ::dji_osdk_ros::SDKControlAuthorityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_SDKCONTROLAUTHORITY_H
