// Generated by gencpp from file dji_osdk_ros/SetupCameraH264.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264_H
#define DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/SetupCameraH264Request.h>
#include <dji_osdk_ros/SetupCameraH264Response.h>


namespace dji_osdk_ros
{

struct SetupCameraH264
{

typedef SetupCameraH264Request Request;
typedef SetupCameraH264Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetupCameraH264
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraH264 > {
  static const char* value()
  {
    return "08053824d6e6943daabf1c4c8936b823";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::SetupCameraH264 > {
  static const char* value()
  {
    return "dji_osdk_ros/SetupCameraH264";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraH264Request> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraH264 >
template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraH264Request>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SetupCameraH264 >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SetupCameraH264Request> should match
// service_traits::DataType< ::dji_osdk_ros::SetupCameraH264 >
template<>
struct DataType< ::dji_osdk_ros::SetupCameraH264Request>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SetupCameraH264 >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraH264Response> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraH264 >
template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraH264Response>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SetupCameraH264 >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraH264Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SetupCameraH264Response> should match
// service_traits::DataType< ::dji_osdk_ros::SetupCameraH264 >
template<>
struct DataType< ::dji_osdk_ros::SetupCameraH264Response>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SetupCameraH264 >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraH264Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264_H
