// Generated by gencpp from file dji_osdk_ros/SetupCameraH264Request.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H
#define DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dji_osdk_ros
{
template <class ContainerAllocator>
struct SetupCameraH264Request_
{
  typedef SetupCameraH264Request_<ContainerAllocator> Type;

  SetupCameraH264Request_()
    : request_view(0)
    , start(0)  {
    }
  SetupCameraH264Request_(const ContainerAllocator& _alloc)
    : request_view(0)
    , start(0)  {
  (void)_alloc;
    }



   typedef uint8_t _request_view_type;
  _request_view_type request_view;

   typedef uint8_t _start_type;
  _start_type start;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(FPV_CAMERA)
  #undef FPV_CAMERA
#endif
#if defined(_WIN32) && defined(MAIN_CAMERA)
  #undef MAIN_CAMERA
#endif
#if defined(_WIN32) && defined(VICE_CAMERA)
  #undef VICE_CAMERA
#endif
#if defined(_WIN32) && defined(TOP_CAMERA)
  #undef TOP_CAMERA
#endif

  enum {
    FPV_CAMERA = 7u,
    MAIN_CAMERA = 0u,
    VICE_CAMERA = 1u,
    TOP_CAMERA = 2u,
  };


  typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetupCameraH264Request_

typedef ::dji_osdk_ros::SetupCameraH264Request_<std::allocator<void> > SetupCameraH264Request;

typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request > SetupCameraH264RequestPtr;
typedef boost::shared_ptr< ::dji_osdk_ros::SetupCameraH264Request const> SetupCameraH264RequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator2> & rhs)
{
  return lhs.request_view == rhs.request_view &&
    lhs.start == rhs.start;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator1> & lhs, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dji_osdk_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbc9edd450365b3e5b6c4e71c439e0d4";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbc9edd450365b3eULL;
  static const uint64_t static_value2 = 0x5b6c4e71c439e0d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dji_osdk_ros/SetupCameraH264Request";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#constant for vga image frequency\n"
"uint8 FPV_CAMERA  = 7\n"
"uint8 MAIN_CAMERA = 0\n"
"uint8 VICE_CAMERA = 1\n"
"uint8 TOP_CAMERA  = 2\n"
"\n"
"# use above constants to config freq.\n"
"uint8 request_view\n"
"\n"
"# 1 for start camera stream, 0 for stop\n"
"uint8 start\n"
"\n"
;
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_view);
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetupCameraH264Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dji_osdk_ros::SetupCameraH264Request_<ContainerAllocator>& v)
  {
    s << indent << "request_view: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request_view);
    s << indent << "start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_SETUPCAMERAH264REQUEST_H
