// Generated by gencpp from file dji_osdk_ros/SetupCameraStream.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_SETUPCAMERASTREAM_H
#define DJI_OSDK_ROS_MESSAGE_SETUPCAMERASTREAM_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/SetupCameraStreamRequest.h>
#include <dji_osdk_ros/SetupCameraStreamResponse.h>


namespace dji_osdk_ros
{

struct SetupCameraStream
{

typedef SetupCameraStreamRequest Request;
typedef SetupCameraStreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetupCameraStream
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraStream > {
  static const char* value()
  {
    return "e0732f307563f64841a2e5c6880f32d3";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraStream&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::SetupCameraStream > {
  static const char* value()
  {
    return "dji_osdk_ros/SetupCameraStream";
  }

  static const char* value(const ::dji_osdk_ros::SetupCameraStream&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraStreamRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraStream >
template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraStreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraStreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SetupCameraStreamRequest> should match
// service_traits::DataType< ::dji_osdk_ros::SetupCameraStream >
template<>
struct DataType< ::dji_osdk_ros::SetupCameraStreamRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraStreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraStreamResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::SetupCameraStream >
template<>
struct MD5Sum< ::dji_osdk_ros::SetupCameraStreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraStreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::SetupCameraStreamResponse> should match
// service_traits::DataType< ::dji_osdk_ros::SetupCameraStream >
template<>
struct DataType< ::dji_osdk_ros::SetupCameraStreamResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::SetupCameraStream >::value();
  }
  static const char* value(const ::dji_osdk_ros::SetupCameraStreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_SETUPCAMERASTREAM_H
