// Generated by gencpp from file dji_osdk_ros/StereoVGASubscription.msg
// DO NOT EDIT!


#ifndef DJI_OSDK_ROS_MESSAGE_STEREOVGASUBSCRIPTION_H
#define DJI_OSDK_ROS_MESSAGE_STEREOVGASUBSCRIPTION_H

#include <ros/service_traits.h>


#include <dji_osdk_ros/StereoVGASubscriptionRequest.h>
#include <dji_osdk_ros/StereoVGASubscriptionResponse.h>


namespace dji_osdk_ros
{

struct StereoVGASubscription
{

typedef StereoVGASubscriptionRequest Request;
typedef StereoVGASubscriptionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StereoVGASubscription
} // namespace dji_osdk_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dji_osdk_ros::StereoVGASubscription > {
  static const char* value()
  {
    return "a636307470f5a4e2ecf4fbcb4aeca4ed";
  }

  static const char* value(const ::dji_osdk_ros::StereoVGASubscription&) { return value(); }
};

template<>
struct DataType< ::dji_osdk_ros::StereoVGASubscription > {
  static const char* value()
  {
    return "dji_osdk_ros/StereoVGASubscription";
  }

  static const char* value(const ::dji_osdk_ros::StereoVGASubscription&) { return value(); }
};


// service_traits::MD5Sum< ::dji_osdk_ros::StereoVGASubscriptionRequest> should match
// service_traits::MD5Sum< ::dji_osdk_ros::StereoVGASubscription >
template<>
struct MD5Sum< ::dji_osdk_ros::StereoVGASubscriptionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::StereoVGASubscription >::value();
  }
  static const char* value(const ::dji_osdk_ros::StereoVGASubscriptionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::StereoVGASubscriptionRequest> should match
// service_traits::DataType< ::dji_osdk_ros::StereoVGASubscription >
template<>
struct DataType< ::dji_osdk_ros::StereoVGASubscriptionRequest>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::StereoVGASubscription >::value();
  }
  static const char* value(const ::dji_osdk_ros::StereoVGASubscriptionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dji_osdk_ros::StereoVGASubscriptionResponse> should match
// service_traits::MD5Sum< ::dji_osdk_ros::StereoVGASubscription >
template<>
struct MD5Sum< ::dji_osdk_ros::StereoVGASubscriptionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dji_osdk_ros::StereoVGASubscription >::value();
  }
  static const char* value(const ::dji_osdk_ros::StereoVGASubscriptionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dji_osdk_ros::StereoVGASubscriptionResponse> should match
// service_traits::DataType< ::dji_osdk_ros::StereoVGASubscription >
template<>
struct DataType< ::dji_osdk_ros::StereoVGASubscriptionResponse>
{
  static const char* value()
  {
    return DataType< ::dji_osdk_ros::StereoVGASubscription >::value();
  }
  static const char* value(const ::dji_osdk_ros::StereoVGASubscriptionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DJI_OSDK_ROS_MESSAGE_STEREOVGASUBSCRIPTION_H
