(cl:defpackage ardrone_as-msg
  (:use )
  (:export
   "<ARDRONEACTION>"
   "ARDRONEACTION"
   "<ARDRONEACTIONFEEDBACK>"
   "ARDRONEACTIONFEEDBACK"
   "<ARDRONEACTIONGOAL>"
   "ARDRONEACTIONGOAL"
   "<ARDRONEACTIONRESULT>"
   "ARDRONEACTIONRESULT"
   "<ARDRONEFEEDBACK>"
   "ARDRONEFEEDBACK"
   "<ARDRONEGOAL>"
   "ARDRONEGOAL"
   "<ARDRONERESULT>"
   "ARDRONERESULT"
  ))

