// Generated by gencpp from file takeoff/GroundtruthAltitude.msg
// DO NOT EDIT!


#ifndef TAKEOFF_MESSAGE_GROUNDTRUTHALTITUDE_H
#define TAKEOFF_MESSAGE_GROUNDTRUTHALTITUDE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace takeoff
{
template <class ContainerAllocator>
struct GroundtruthAltitude_
{
  typedef GroundtruthAltitude_<ContainerAllocator> Type;

  GroundtruthAltitude_()
    : header()
    , gt_altitude(0.0)  {
    }
  GroundtruthAltitude_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gt_altitude(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _gt_altitude_type;
  _gt_altitude_type gt_altitude;





  typedef boost::shared_ptr< ::takeoff::GroundtruthAltitude_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::takeoff::GroundtruthAltitude_<ContainerAllocator> const> ConstPtr;

}; // struct GroundtruthAltitude_

typedef ::takeoff::GroundtruthAltitude_<std::allocator<void> > GroundtruthAltitude;

typedef boost::shared_ptr< ::takeoff::GroundtruthAltitude > GroundtruthAltitudePtr;
typedef boost::shared_ptr< ::takeoff::GroundtruthAltitude const> GroundtruthAltitudeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::takeoff::GroundtruthAltitude_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace takeoff

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'takeoff': ['/home/huy/Autonomous-Landing-on-Moving-Platform/pablo_uav_system_ws/src/takeoff/msg', '/home/huy/Autonomous-Landing-on-Moving-Platform/pablo_uav_system_ws/src/takeoff/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::takeoff::GroundtruthAltitude_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::takeoff::GroundtruthAltitude_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::takeoff::GroundtruthAltitude_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "018e1e2bc342cacf34a44088104e49e3";
  }

  static const char* value(const ::takeoff::GroundtruthAltitude_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x018e1e2bc342cacfULL;
  static const uint64_t static_value2 = 0x34a44088104e49e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "takeoff/GroundtruthAltitude";
  }

  static const char* value(const ::takeoff::GroundtruthAltitude_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 gt_altitude\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::takeoff::GroundtruthAltitude_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gt_altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GroundtruthAltitude_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::takeoff::GroundtruthAltitude_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::takeoff::GroundtruthAltitude_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gt_altitude: ";
    Printer<float>::stream(s, indent + "  ", v.gt_altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TAKEOFF_MESSAGE_GROUNDTRUTHALTITUDE_H
