// Generated by gencpp from file ardrone_autonomy/FlightAnimRequest.msg
// DO NOT EDIT!


#ifndef ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIMREQUEST_H
#define ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardrone_autonomy
{
template <class ContainerAllocator>
struct FlightAnimRequest_
{
  typedef FlightAnimRequest_<ContainerAllocator> Type;

  FlightAnimRequest_()
    : type(0)
    , duration(0)  {
    }
  FlightAnimRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint32_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FlightAnimRequest_

typedef ::ardrone_autonomy::FlightAnimRequest_<std::allocator<void> > FlightAnimRequest;

typedef boost::shared_ptr< ::ardrone_autonomy::FlightAnimRequest > FlightAnimRequestPtr;
typedef boost::shared_ptr< ::ardrone_autonomy::FlightAnimRequest const> FlightAnimRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator1> & lhs, const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator1> & lhs, const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ardrone_autonomy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1babbb93af7ae39105f8dba705eb91ac";
  }

  static const char* value(const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1babbb93af7ae391ULL;
  static const uint64_t static_value2 = 0x05f8dba705eb91acULL;
};

template<class ContainerAllocator>
struct DataType< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardrone_autonomy/FlightAnimRequest";
  }

  static const char* value(const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 0 : ARDRONE_ANIM_PHI_M30_DEG\n"
"# 1 : ARDRONE_ANIM_PHI_30_DEG\n"
"# 2 : ARDRONE_ANIM_THETA_M30_DEG\n"
"# 3 : ARDRONE_ANIM_THETA_30_DEG\n"
"# 4 : ARDRONE_ANIM_THETA_20DEG_YAW_200DEG\n"
"# 5 : ARDRONE_ANIM_THETA_20DEG_YAW_M200DEG\n"
"# 6 : ARDRONE_ANIM_TURNAROUND\n"
"# 7 : ARDRONE_ANIM_TURNAROUND_GODOWN\n"
"# 8 : ARDRONE_ANIM_YAW_SHAKE\n"
"# 9 : ARDRONE_ANIM_YAW_DANCE\n"
"# 10: ARDRONE_ANIM_PHI_DANCE\n"
"# 11: ARDRONE_ANIM_THETA_DANCE\n"
"# 12: ARDRONE_ANIM_VZ_DANCE\n"
"# 13: ARDRONE_ANIM_WAVE\n"
"# 14: ARDRONE_ANIM_PHI_THETA_MIXED\n"
"# 15: ARDRONE_ANIM_DOUBLE_PHI_THETA_MIXED\n"
"# 16: ARDRONE_ANIM_FLIP_AHEAD\n"
"# 17: ARDRONE_ANIM_FLIP_BEHIND\n"
"# 18: ARDRONE_ANIM_FLIP_LEFT\n"
"# 19: ARDRONE_ANIM_FLIP_RIGHT\n"
"\n"
"uint8 type\n"
"\n"
"# In Milliseconds\n"
"# 0 For Default Duration (Recommended)\n"
"uint32 duration\n"
"\n"
;
  }

  static const char* value(const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FlightAnimRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardrone_autonomy::FlightAnimRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "duration: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDRONE_AUTONOMY_MESSAGE_FLIGHTANIMREQUEST_H
