# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/GetWholeBatteryInfoRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GetWholeBatteryInfoRequest(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "dji_osdk_ros/GetWholeBatteryInfoRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#request
"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetWholeBatteryInfoRequest, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/GetWholeBatteryInfoResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dji_osdk_ros.msg

class GetWholeBatteryInfoResponse(genpy.Message):
  _md5sum = "a954f2c109885a4dd2f5564d3eb1433a"
  _type = "dji_osdk_ros/GetWholeBatteryInfoResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """#response
BatteryWholeInfo battery_whole_info

================================================================================
MSG: dji_osdk_ros/BatteryWholeInfo
uint16  remainFlyTime             # remain fly time(s)
uint16  goHomeNeedTime            # Time required for the gohome flight (s)
uint16  landNeedTime              # Time required for the land flight (s).max value:100*/
uint16  goHomeNeedCapacity        # Capacity required for the gohome flight (%).max value:100*/
uint16  landNeedCapacity          # Capacity required for the land flight (%).max value:100*/
float32 safeFlyRadius             # Safe flight area radius (m)*/
float32 capacityConsumeSpeed      # (mAh/sec)*/
BatteryState batteryState
uint8   goHomeCountDownState      # Countdown status of smart battery gohome
                                   # 0/2:not in gohome state
                                   # 1  :in gohome state
                                   #
uint8   gohomeCountDownvalue      # uint:s.max value:10
uint16  voltage                   # mv
uint8   batteryCapacityPercentage # uint:%.max value:100
uint8   lowBatteryAlarmThreshold
uint8   lowBatteryAlarmEnable
uint8   seriousLowBatteryAlarmThreshold
uint8   seriousLowBatteryAlarmEnable  
================================================================================
MSG: dji_osdk_ros/BatteryState
uint8 voltageNotSafety # Generally caused by low temperature, the battery has electricity,
                       # but the battery voltage is too low.
uint8 veryLowVoltageAlarm
uint8 LowVoltageAlarm
uint8 seriousLowCapacityAlarm
uint8 LowCapacityAlarm"""
  __slots__ = ['battery_whole_info']
  _slot_types = ['dji_osdk_ros/BatteryWholeInfo']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       battery_whole_info

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GetWholeBatteryInfoResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.battery_whole_info is None:
        self.battery_whole_info = dji_osdk_ros.msg.BatteryWholeInfo()
    else:
      self.battery_whole_info = dji_osdk_ros.msg.BatteryWholeInfo()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5H2f7BH5B().pack(_x.battery_whole_info.remainFlyTime, _x.battery_whole_info.goHomeNeedTime, _x.battery_whole_info.landNeedTime, _x.battery_whole_info.goHomeNeedCapacity, _x.battery_whole_info.landNeedCapacity, _x.battery_whole_info.safeFlyRadius, _x.battery_whole_info.capacityConsumeSpeed, _x.battery_whole_info.batteryState.voltageNotSafety, _x.battery_whole_info.batteryState.veryLowVoltageAlarm, _x.battery_whole_info.batteryState.LowVoltageAlarm, _x.battery_whole_info.batteryState.seriousLowCapacityAlarm, _x.battery_whole_info.batteryState.LowCapacityAlarm, _x.battery_whole_info.goHomeCountDownState, _x.battery_whole_info.gohomeCountDownvalue, _x.battery_whole_info.voltage, _x.battery_whole_info.batteryCapacityPercentage, _x.battery_whole_info.lowBatteryAlarmThreshold, _x.battery_whole_info.lowBatteryAlarmEnable, _x.battery_whole_info.seriousLowBatteryAlarmThreshold, _x.battery_whole_info.seriousLowBatteryAlarmEnable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.battery_whole_info is None:
        self.battery_whole_info = dji_osdk_ros.msg.BatteryWholeInfo()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.battery_whole_info.remainFlyTime, _x.battery_whole_info.goHomeNeedTime, _x.battery_whole_info.landNeedTime, _x.battery_whole_info.goHomeNeedCapacity, _x.battery_whole_info.landNeedCapacity, _x.battery_whole_info.safeFlyRadius, _x.battery_whole_info.capacityConsumeSpeed, _x.battery_whole_info.batteryState.voltageNotSafety, _x.battery_whole_info.batteryState.veryLowVoltageAlarm, _x.battery_whole_info.batteryState.LowVoltageAlarm, _x.battery_whole_info.batteryState.seriousLowCapacityAlarm, _x.battery_whole_info.batteryState.LowCapacityAlarm, _x.battery_whole_info.goHomeCountDownState, _x.battery_whole_info.gohomeCountDownvalue, _x.battery_whole_info.voltage, _x.battery_whole_info.batteryCapacityPercentage, _x.battery_whole_info.lowBatteryAlarmThreshold, _x.battery_whole_info.lowBatteryAlarmEnable, _x.battery_whole_info.seriousLowBatteryAlarmThreshold, _x.battery_whole_info.seriousLowBatteryAlarmEnable,) = _get_struct_5H2f7BH5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5H2f7BH5B().pack(_x.battery_whole_info.remainFlyTime, _x.battery_whole_info.goHomeNeedTime, _x.battery_whole_info.landNeedTime, _x.battery_whole_info.goHomeNeedCapacity, _x.battery_whole_info.landNeedCapacity, _x.battery_whole_info.safeFlyRadius, _x.battery_whole_info.capacityConsumeSpeed, _x.battery_whole_info.batteryState.voltageNotSafety, _x.battery_whole_info.batteryState.veryLowVoltageAlarm, _x.battery_whole_info.batteryState.LowVoltageAlarm, _x.battery_whole_info.batteryState.seriousLowCapacityAlarm, _x.battery_whole_info.batteryState.LowCapacityAlarm, _x.battery_whole_info.goHomeCountDownState, _x.battery_whole_info.gohomeCountDownvalue, _x.battery_whole_info.voltage, _x.battery_whole_info.batteryCapacityPercentage, _x.battery_whole_info.lowBatteryAlarmThreshold, _x.battery_whole_info.lowBatteryAlarmEnable, _x.battery_whole_info.seriousLowBatteryAlarmThreshold, _x.battery_whole_info.seriousLowBatteryAlarmEnable))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.battery_whole_info is None:
        self.battery_whole_info = dji_osdk_ros.msg.BatteryWholeInfo()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.battery_whole_info.remainFlyTime, _x.battery_whole_info.goHomeNeedTime, _x.battery_whole_info.landNeedTime, _x.battery_whole_info.goHomeNeedCapacity, _x.battery_whole_info.landNeedCapacity, _x.battery_whole_info.safeFlyRadius, _x.battery_whole_info.capacityConsumeSpeed, _x.battery_whole_info.batteryState.voltageNotSafety, _x.battery_whole_info.batteryState.veryLowVoltageAlarm, _x.battery_whole_info.batteryState.LowVoltageAlarm, _x.battery_whole_info.batteryState.seriousLowCapacityAlarm, _x.battery_whole_info.batteryState.LowCapacityAlarm, _x.battery_whole_info.goHomeCountDownState, _x.battery_whole_info.gohomeCountDownvalue, _x.battery_whole_info.voltage, _x.battery_whole_info.batteryCapacityPercentage, _x.battery_whole_info.lowBatteryAlarmThreshold, _x.battery_whole_info.lowBatteryAlarmEnable, _x.battery_whole_info.seriousLowBatteryAlarmThreshold, _x.battery_whole_info.seriousLowBatteryAlarmEnable,) = _get_struct_5H2f7BH5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5H2f7BH5B = None
def _get_struct_5H2f7BH5B():
    global _struct_5H2f7BH5B
    if _struct_5H2f7BH5B is None:
        _struct_5H2f7BH5B = struct.Struct("<5H2f7BH5B")
    return _struct_5H2f7BH5B
class GetWholeBatteryInfo(object):
  _type          = 'dji_osdk_ros/GetWholeBatteryInfo'
  _md5sum = 'a954f2c109885a4dd2f5564d3eb1433a'
  _request_class  = GetWholeBatteryInfoRequest
  _response_class = GetWholeBatteryInfoResponse
