nodes:
  - id: 1
    node_name: Take_Off_Landing
    node_type: SEQUENCE
    task: LAND
    parameters: ""
    is_recurrent: true
    activate: true
    parent: 0
  - id: 2
    node_name: Take_Off
    node_type: TASK
    task: TAKE_OFF
    parameters: ""
    is_recurrent: false
    activate: false
    parent: 1
  - id: 3
    node_name: Land
    node_type: TASK
    task: LAND
    parameters: ""
    is_recurrent: false
    activate: false
    parent: 1