obstacle_range: 8
raytrace_range: 30.0

footprint: [[0.45, -0.40], [0.45, 0.4], [-0.45,0.4], [-0.45, -0.4]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.7

obstacle_layer:
   observation_sources: merged_laser
   merged_laser: {data_type: LaserScan, topic: /merged_scan, marking: true, clearing: true}
   track_unknown_space: true
   unkown_cost_value: 0.1

