global_costmap:
  global_frame: /summit_xl_map
  robot_base_frame: /summit_xl_base_footprint
  update_frequency: 2.0
  static_map: true
  width: 200.0
  height: 200.0 

  inflation_layer:
    inflation_radius: 0.5
  
  plugins:
    - 
      name: obstacle_layer
      type: "costmap_2d::VoxelLayer"
    - 
      name: static_map
      type: "costmap_2d::StaticLayer"
    - 
      name: inflation_layer
      type: "costmap_2d::InflationLayer"
    - 
      name: rgbd_obstacle_layer
      type: "costmap_2d::VoxelLayer"
  rgbd_obstacle_layer:
    front_rgbd_to_scan:
      observation_persistence: 10.0
  
  static_map:
      lethal_cost_threshold: 70
      static_map: true
      track_unknown_space: false
      unknown_cost_value: 1
      trinary_costmap: false
      use_maximum: true

