local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequence: 5.0
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.05 #0.05
  
  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.0
  inflation_layer:
    inflation_radius: 0.7
    cost_scaling_factor: 5.0
