controller_frequency: 20.0
controller_patience: 30.0
planner_frequency: 0.2
planner_patience: 0.0

conservative_reset_dist: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 0.0
oscillation_distance: 0.5
