# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/BatteryState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BatteryState(genpy.Message):
  _md5sum = "5243c6a8356e946f828c69a991da7334"
  _type = "dji_osdk_ros/BatteryState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 voltageNotSafety # Generally caused by low temperature, the battery has electricity,
                       # but the battery voltage is too low.
uint8 veryLowVoltageAlarm
uint8 LowVoltageAlarm
uint8 seriousLowCapacityAlarm
uint8 LowCapacityAlarm"""
  __slots__ = ['voltageNotSafety','veryLowVoltageAlarm','LowVoltageAlarm','seriousLowCapacityAlarm','LowCapacityAlarm']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       voltageNotSafety,veryLowVoltageAlarm,LowVoltageAlarm,seriousLowCapacityAlarm,LowCapacityAlarm

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BatteryState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.voltageNotSafety is None:
        self.voltageNotSafety = 0
      if self.veryLowVoltageAlarm is None:
        self.veryLowVoltageAlarm = 0
      if self.LowVoltageAlarm is None:
        self.LowVoltageAlarm = 0
      if self.seriousLowCapacityAlarm is None:
        self.seriousLowCapacityAlarm = 0
      if self.LowCapacityAlarm is None:
        self.LowCapacityAlarm = 0
    else:
      self.voltageNotSafety = 0
      self.veryLowVoltageAlarm = 0
      self.LowVoltageAlarm = 0
      self.seriousLowCapacityAlarm = 0
      self.LowCapacityAlarm = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.voltageNotSafety, _x.veryLowVoltageAlarm, _x.LowVoltageAlarm, _x.seriousLowCapacityAlarm, _x.LowCapacityAlarm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.voltageNotSafety, _x.veryLowVoltageAlarm, _x.LowVoltageAlarm, _x.seriousLowCapacityAlarm, _x.LowCapacityAlarm,) = _get_struct_5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5B().pack(_x.voltageNotSafety, _x.veryLowVoltageAlarm, _x.LowVoltageAlarm, _x.seriousLowCapacityAlarm, _x.LowCapacityAlarm))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.voltageNotSafety, _x.veryLowVoltageAlarm, _x.LowVoltageAlarm, _x.seriousLowCapacityAlarm, _x.LowCapacityAlarm,) = _get_struct_5B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5B = None
def _get_struct_5B():
    global _struct_5B
    if _struct_5B is None:
        _struct_5B = struct.Struct("<5B")
    return _struct_5B
