# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/WaypointV2.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import dji_osdk_ros.msg

class WaypointV2(genpy.Message):
  _md5sum = "389194e4db4c519440c6686894700c6a"
  _type = "dji_osdk_ros/WaypointV2"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# The struct represents a target point in the waypoint mission. For a waypoint

#constant for flightpathMode
uint8 DJIWaypointV2FlightPathModeGoToPointAlongACurve = 0  #In the mission, the aircraft will go to the waypoint along a curve and fly past the waypoint.
uint8 DJIWaypointV2FlightPathModeGoToPointAlongACurveAndStop = 1 #In the mission, the aircraft will go to the waypoint along a curve and stop at the waypoint.
uint8 DJIWaypointV2FlightPathModeGoToPointInAStraightLineAndStop = 2  #In the mission, the aircraft will go to the waypoint along a straight line and stop at the waypoint.
uint8 DJIWaypointV2FlightPathModeCoordinateTurn = 3   #In the mission, the aircraft will fly from the previous waypoint to the next waypoint along a smooth curve without stopping at this waypoint.
                                                      #the next in a curved motion,  adhering to the ``DJIWaypointV2_dampingDistance``, which is
                                                      #set in ``DJIWaypointV2``.
uint8 DJIWaypointV2FlightPathModeGoToFirstPointAlongAStraightLine = 4  # In the mission, the aircraft will go to the first waypoint along a straight line.
                                                                       # This is only valid for the first waypoint.
uint8 DJIWaypointV2FlightPathModeStraightOut = 5   # Straight exit the Last waypoint, Only valid for last waypoint.
uint8 DJIWaypointV2FlightPathModeUnknown = 255    # Unknown

#constant for headMode
uint8 DJIWaypointV2HeadingModeAuto = 0    # Aircraft's heading will always be in the direction of flight.
uint8 DJIWaypointV2HeadingFixed    = 1    # Aircraft's heading will be set to the heading when reaching the first waypoint.
                                          # Before reaching the first waypoint, the aircraft's heading can be controlled by
                                          # the remote controller. When the aircraft reaches the first waypoint, its
                                          # heading will be fixed.
uint8 DJIWaypointV2HeadingManual   = 2    # The aircraft's heading in the mission can be controlled by the remote controller.
uint8 DJIWaypointV2HeadingWaypointCustom = 3  # In the mission, the aircraft's heading will change dynamically and adapt to the heading set at the next waypoint.
                                               # See ``DJIWaypointV2_heading`` to preset the heading.
uint8 DJIWaypointV2HeadingTowardPointOfInterest = 4 # Aircraft's heading will always toward point of interest.
                                                    # using ``DJIWaypointV2_pointOfInterest`` setting point of interest coordiate and ``DJIWaypointV2_pointOfInterestAltitude``
                                                    # setting point of interset altitute.
uint8 DJIWaypointV2HeadingGimbalYawFollow  = 5   # The aircraft's heading rotate simultaneously with its gimbal's yaw.
uint8 DJIWaypointV2HeadingUnknown = 255         # Unknown.

#constant for turnMode
uint8 DJIWaypointV2TurnModeClockwise = 0  # The aircraft's heading rotates clockwise.
uint8 DJIWaypointV2TurnModeCounterClockwise = 1   # The aircraft's heading rotates counterclockwise.
uint8 DJIWaypointV2TurnModeUnknown = 255    # Changes the heading of the aircraft by rotating the aircraft anti-clockwise.



#  mission, a flight route  consists of multiple `WaypointV2` objects.
float64 longitude  # waypoint position relative to WayPointV2InitSettings's reference point.unit: m
float64 latitude
float32 relativeHeight  # relative to takeoff height
uint8   waypointType    # Waypoint flight path mode
uint8   headingMode     # Represents current aircraft's heading mode on current waypoint.
WaypointV2Config  config          # Represents current waypoint's speed config.
uint16  dampingDistance
float32 heading         # The heading to which the aircraft will rotate by the time it reaches the
                        # waypoint. The aircraft heading  will gradually change between two waypoints with
                        # different headings if the waypoint  mission's `headingMode` is set  to
                        # 'DJIWaypointV2_DJIWaypointV2HeadingMode_WaypointCustom`. A heading has a range of
                        # [-180, 180] degrees, where 0 represents True North.
uint8 turnMode          # Determines whether the aircraft will turn clockwise or anticlockwise when
                        # changing its heading.
# Property is used when ``DJIWaypointV2_headingMode`` is
# ``DJIWaypointV2_DJIWaypointV2HeadingMode_TowardPointOfInterest``.
# Aircraft will always be heading to point while executing mission. Default is
# "kCLLocationCoordinate2DInvalid".
float32 positionX       # X distance to reference point, North is positive
float32 positionY       # Y distance to reference point, East is positive
float32 positionZ       # Z distance to reference point, UP is positive

# While the aircraft is travelling between waypoints, you can offset its speed by
# using the throttle joystick on the remote controller. "maxFlightSpeed" is this
# offset when the joystick is pushed to maximum deflection. For example, If
# maxFlightSpeed is 10 m/s, then pushing the throttle joystick all the way up will
# add 10 m/s to the aircraft speed, while pushing down will subtract 10 m/s from
# the aircraft speed. If the remote controller stick is not at maximum deflection,
# then the offset speed will be interpolated between "[0, maxFlightSpeed]"" with a
# resolution of 1000 steps. If the offset speed is negative, then the aircraft
# will fly backwards to previous waypoints. When it reaches the first waypoint, it
# will then hover in place until a positive speed is applied. "maxFlightSpeed" has
# a range of [2,15] m/s.
float32 maxFlightSpeed

# The base automatic speed of the aircraft as it moves between waypoints with
# range [-15, 15] m/s. The aircraft's actual speed is a combination of the base
# automatic speed, and the speed control given by the throttle joystick on the
# remote controller. If "autoFlightSpeed >0": Actual speed is "autoFlightSpeed" +
# Joystick Speed (with combined max of "maxFlightSpeed") If "autoFlightSpeed =0":
# Actual speed is controlled only by the remote controller joystick. If
# autoFlightSpeed <0" and the aircraft is at the first waypoint, the aircraft
# will hover in place until the speed is made positive by the remote controller
# joystick. In flight controller firmware 3.2.10.0 or above, different speeds
# between individual waypoints can also be set in waypoint objects which will
# overwrite "autoFlightSpeed".
float32 autoFlightSpeed
================================================================================
MSG: dji_osdk_ros/WaypointV2Config
# Represents current waypoint's speed config.
# 0: set local waypoint's cruise speed,
# 1: unset global waypoint's cruise speed*/
uint8  useLocalCruiseVel
# 0: set local waypoint's max speed,
# 1: unset global waypoint's max speed*/
uint8  useLocalMaxVel"""
  # Pseudo-constants
  DJIWaypointV2FlightPathModeGoToPointAlongACurve = 0
  DJIWaypointV2FlightPathModeGoToPointAlongACurveAndStop = 1
  DJIWaypointV2FlightPathModeGoToPointInAStraightLineAndStop = 2
  DJIWaypointV2FlightPathModeCoordinateTurn = 3
  DJIWaypointV2FlightPathModeGoToFirstPointAlongAStraightLine = 4
  DJIWaypointV2FlightPathModeStraightOut = 5
  DJIWaypointV2FlightPathModeUnknown = 255
  DJIWaypointV2HeadingModeAuto = 0
  DJIWaypointV2HeadingFixed = 1
  DJIWaypointV2HeadingManual = 2
  DJIWaypointV2HeadingWaypointCustom = 3
  DJIWaypointV2HeadingTowardPointOfInterest = 4
  DJIWaypointV2HeadingGimbalYawFollow = 5
  DJIWaypointV2HeadingUnknown = 255
  DJIWaypointV2TurnModeClockwise = 0
  DJIWaypointV2TurnModeCounterClockwise = 1
  DJIWaypointV2TurnModeUnknown = 255

  __slots__ = ['longitude','latitude','relativeHeight','waypointType','headingMode','config','dampingDistance','heading','turnMode','positionX','positionY','positionZ','maxFlightSpeed','autoFlightSpeed']
  _slot_types = ['float64','float64','float32','uint8','uint8','dji_osdk_ros/WaypointV2Config','uint16','float32','uint8','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       longitude,latitude,relativeHeight,waypointType,headingMode,config,dampingDistance,heading,turnMode,positionX,positionY,positionZ,maxFlightSpeed,autoFlightSpeed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointV2, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.relativeHeight is None:
        self.relativeHeight = 0.
      if self.waypointType is None:
        self.waypointType = 0
      if self.headingMode is None:
        self.headingMode = 0
      if self.config is None:
        self.config = dji_osdk_ros.msg.WaypointV2Config()
      if self.dampingDistance is None:
        self.dampingDistance = 0
      if self.heading is None:
        self.heading = 0.
      if self.turnMode is None:
        self.turnMode = 0
      if self.positionX is None:
        self.positionX = 0.
      if self.positionY is None:
        self.positionY = 0.
      if self.positionZ is None:
        self.positionZ = 0.
      if self.maxFlightSpeed is None:
        self.maxFlightSpeed = 0.
      if self.autoFlightSpeed is None:
        self.autoFlightSpeed = 0.
    else:
      self.longitude = 0.
      self.latitude = 0.
      self.relativeHeight = 0.
      self.waypointType = 0
      self.headingMode = 0
      self.config = dji_osdk_ros.msg.WaypointV2Config()
      self.dampingDistance = 0
      self.heading = 0.
      self.turnMode = 0
      self.positionX = 0.
      self.positionY = 0.
      self.positionZ = 0.
      self.maxFlightSpeed = 0.
      self.autoFlightSpeed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2df4BHfB5f().pack(_x.longitude, _x.latitude, _x.relativeHeight, _x.waypointType, _x.headingMode, _x.config.useLocalCruiseVel, _x.config.useLocalMaxVel, _x.dampingDistance, _x.heading, _x.turnMode, _x.positionX, _x.positionY, _x.positionZ, _x.maxFlightSpeed, _x.autoFlightSpeed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.config is None:
        self.config = dji_osdk_ros.msg.WaypointV2Config()
      end = 0
      _x = self
      start = end
      end += 51
      (_x.longitude, _x.latitude, _x.relativeHeight, _x.waypointType, _x.headingMode, _x.config.useLocalCruiseVel, _x.config.useLocalMaxVel, _x.dampingDistance, _x.heading, _x.turnMode, _x.positionX, _x.positionY, _x.positionZ, _x.maxFlightSpeed, _x.autoFlightSpeed,) = _get_struct_2df4BHfB5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2df4BHfB5f().pack(_x.longitude, _x.latitude, _x.relativeHeight, _x.waypointType, _x.headingMode, _x.config.useLocalCruiseVel, _x.config.useLocalMaxVel, _x.dampingDistance, _x.heading, _x.turnMode, _x.positionX, _x.positionY, _x.positionZ, _x.maxFlightSpeed, _x.autoFlightSpeed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.config is None:
        self.config = dji_osdk_ros.msg.WaypointV2Config()
      end = 0
      _x = self
      start = end
      end += 51
      (_x.longitude, _x.latitude, _x.relativeHeight, _x.waypointType, _x.headingMode, _x.config.useLocalCruiseVel, _x.config.useLocalMaxVel, _x.dampingDistance, _x.heading, _x.turnMode, _x.positionX, _x.positionY, _x.positionZ, _x.maxFlightSpeed, _x.autoFlightSpeed,) = _get_struct_2df4BHfB5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2df4BHfB5f = None
def _get_struct_2df4BHfB5f():
    global _struct_2df4BHfB5f
    if _struct_2df4BHfB5f is None:
        _struct_2df4BHfB5f = struct.Struct("<2df4BHfB5f")
    return _struct_2df4BHfB5f
