# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dji_osdk_ros/WaypointV2MissionStatePush.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WaypointV2MissionStatePush(genpy.Message):
  _md5sum = "8f0a910f9304e8d0a921ad51a303b666"
  _type = "dji_osdk_ros/WaypointV2MissionStatePush"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int8   commonDataVersion
uint16 commonDataLen
uint16 curWaypointIndex
uint8  state  #0x0:ground station not start. 0x1:mission prepared. 0x2:enter mission.
               #0x3:execute flying route mission.
               #0x4:pause state. 0x5:enter mission after ending pause.
               #0x6:exit mission.
uint16 velocity #uint:0.01m/s"""
  __slots__ = ['commonDataVersion','commonDataLen','curWaypointIndex','state','velocity']
  _slot_types = ['int8','uint16','uint16','uint8','uint16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       commonDataVersion,commonDataLen,curWaypointIndex,state,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WaypointV2MissionStatePush, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.commonDataVersion is None:
        self.commonDataVersion = 0
      if self.commonDataLen is None:
        self.commonDataLen = 0
      if self.curWaypointIndex is None:
        self.curWaypointIndex = 0
      if self.state is None:
        self.state = 0
      if self.velocity is None:
        self.velocity = 0
    else:
      self.commonDataVersion = 0
      self.commonDataLen = 0
      self.curWaypointIndex = 0
      self.state = 0
      self.velocity = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_b2HBH().pack(_x.commonDataVersion, _x.commonDataLen, _x.curWaypointIndex, _x.state, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.commonDataVersion, _x.commonDataLen, _x.curWaypointIndex, _x.state, _x.velocity,) = _get_struct_b2HBH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_b2HBH().pack(_x.commonDataVersion, _x.commonDataLen, _x.curWaypointIndex, _x.state, _x.velocity))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.commonDataVersion, _x.commonDataLen, _x.curWaypointIndex, _x.state, _x.velocity,) = _get_struct_b2HBH().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_b2HBH = None
def _get_struct_b2HBH():
    global _struct_b2HBH
    if _struct_b2HBH is None:
        _struct_b2HBH = struct.Struct("<b2HBH")
    return _struct_b2HBH
